language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get install -y libev-dev
install:
    - pip install redis
    - pip install -r test-requirements.txt --use-mirrors
    - python setup.py develop
script: flake8 loads && COVERAGE_PROCESS_START=1 nosetests loads/tests
services:
  - redis-server
notifications:
    email:
        - tarek@mozilla.com
        - alexis@mozilla.com
    irc: "irc.mozilla.org#services-dev"
    on_success: change
after_success:
  # Report coverage results to coveralls.io
  - coverage combine
  - pip install coveralls
  - coveralls
