language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get install -y libev-dev
install:
    - pip install -r test-requirements.txt --use-mirrors
    - python setup.py develop
script: flake8 circus && nosetests -sv loads/tests
notifications:
    email:
        - tarek@mozilla.com
        - alexis@mozilla.com
    irc: "irc.mozilla.org#services-dev"
    on_success: change
